"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/aJ2I4nFGPve
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import Link from "next/link";
import {
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenu,
} from "@/components/ui/navigation-menu";

export function Home() {
  return (
    <main>
      <section className="relative">
        <img
          alt="Gallery view"
          className="w-full h-auto object-cover"
          height="600"
          src="/placeholder.svg"
          style={{
            aspectRatio: "1920/600",
            objectFit: "cover",
          }}
          width="1920"
        />
        <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 text-center">
          <h2 className="text-4xl font-bold text-white">BUNTER LEBEN</h2>
          <p className="text-xl text-white mt-4">Art by Anja Borrmeister</p>
        </div>
      </section>
      <section className="py-12 bg-gray-100">
        <div className="max-w-7xl mx-auto px-4 grid grid-cols-3 gap-8">
          <div className="bg-white p-6 shadow rounded-lg">
            <img
              alt="Painting"
              className="w-full h-auto rounded-lg"
              height="240"
              src="/placeholder.svg"
              style={{
                aspectRatio: "360/240",
                objectFit: "cover",
              }}
              width="360"
            />
            <h3 className="mt-4 text-lg font-semibold">Malerei</h3>
            <p className="text-gray-600">
              Bunte Farbwelten aufgetragen mit Pinsel oder Spachtel.
            </p>
            <a className="text-blue-500 mt-2 inline-block" href="#">
              {`MEHR SEHEN >`}
            </a>
          </div>
          <div className="bg-white p-6 shadow rounded-lg">
            <img
              alt="Collage"
              className="w-full h-auto rounded-lg"
              height="240"
              src="/placeholder.svg"
              style={{
                aspectRatio: "360/240",
                objectFit: "cover",
              }}
              width="360"
            />
            <h3 className="mt-4 text-lg font-semibold">Collage</h3>
            <p className="text-gray-600">
              Fundstücke und kleine Schätze verschmelzen zu neuen Objekten.
            </p>
            <a className="text-blue-500 mt-2 inline-block" href="#">
              {`MEHR SEHEN >`}
            </a>
          </div>
          <div className="bg-white p-6 shadow rounded-lg">
            <img
              alt="Watercolor"
              className="w-full h-auto rounded-lg"
              height="240"
              src="/placeholder.svg"
              style={{
                aspectRatio: "360/240",
                objectFit: "cover",
              }}
              width="360"
            />
            <h3 className="mt-4 text-lg font-semibold">Aquarell</h3>
            <p className="text-gray-600">
              Stark fließende Farben und weiche Übergänge. Bilder voller
              Atmosphäre und Leuchtkraft.
            </p>
            <a className="text-blue-500 mt-2 inline-block" href="#">
              {`MEHR SEHEN >`}
            </a>
          </div>
        </div>
      </section>
      <section className="py-12">
        <div className="max-w-7xl mx-auto px-4">
          <div className="flex flex-col items-center text-center">
            <h2 className="text-3xl font-bold">
              DAS GEHEIMNIS DER KUNST LIEGT DARIN, DASS MAN NICHT SUCHT, SONDERN
              FINDET.” – PABLO PICASSO
            </h2>
            <div className="mt-8 w-48 h-1 bg-blue-500" />
          </div>
        </div>
      </section>
      <section className="py-12 bg-gray-100">
        <div className="max-w-7xl mx-auto px-4 grid grid-cols-2 gap-8">
          <div className="bg-white p-6 shadow rounded-lg">
            <img
              alt="Events"
              className="w-full h-auto rounded-lg"
              height="240"
              src="/placeholder.svg"
              style={{
                aspectRatio: "510/240",
                objectFit: "cover",
              }}
              width="510"
            />
            <h3 className="mt-4 text-lg font-semibold">Veranstaltungen</h3>
            <p className="text-gray-600">
              Bei verschiedenen Veranstaltungen über das Jahr verteilt können
              Sie mit mir in Kontakt treten, haben die Möglichkeit Produkte zu
              erwerben welche nicht im Shop erhältlich sind und können spezielle
              Rabattangebote nutzen.
            </p>
            <a className="text-blue-500 mt-2 inline-block" href="#">
              {`MEHR SEHEN >`}
            </a>
          </div>
          <div className="bg-white p-6 shadow rounded-lg">
            <img
              alt="Projects"
              className="w-full h-auto rounded-lg"
              height="240"
              src="/placeholder.svg"
              style={{
                aspectRatio: "510/240",
                objectFit: "cover",
              }}
              width="510"
            />
            <h3 className="mt-4 text-lg font-semibold">Projekte</h3>
            <p className="text-gray-600">
              Gestaltung eines Klaviers für den Hauptbahnhof Dresden im Rahmen
              des Projekts KlangRaum.
            </p>
            <a className="text-blue-500 mt-2 inline-block" href="#">
              {`MEHR SEHEN >`}
            </a>
          </div>
        </div>
      </section>
      <footer className="py-4 bg-white">
        <div className="max-w-7xl mx-auto px-4 text-center">
          <p className="text-gray-600">Anja Borrmeister | bunter leben</p>
        </div>
      </footer>
    </main>
  );
}
